spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo
    username: root
    password: Vv123
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-init-sql: SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci;
  jpa:
    open-in-view: true
    properties.hibernate.hbm2ddl.auto: update
    properties.hibernate.enable_lazy_load_no_trans: true
server:
  port: 8888

#logging:
#  level.root: debug
